
apiVersion: v1
kind: Service
metadata:
  name: daytrader2ee5
  labels:
    app: daytrader2ee5
spec:
  ports:
    - port: 9080
  selector:
    app: daytrader2ee5
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: daytrader2ee5
  name: daytrader2ee5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daytrader2ee5
    spec:
      containers:
      - image: mycluster.icp:8500/default/daytrader2ee5:latest
        name: daytrader2ee5
        ports:
        - containerPort: 9080
          protocol: TCP
